Matrix Multiplication(1.1)
ElenaBakova/Homeworks pull request #55
Opened 2021-09-11 12:17 UTC by ElenaBakova

2021-09-22 16:01 UTC, yurii-litvinov requested changes

2021-09-22 16:01 UTC, yurii-litvinov commented on Semester3/Homework1/MatrixMultiplication/Program.cs
> +            Matrix size = 500x2000, average = 77.5747sec, standard deviation 143.8739sec
Что-то не так со среднеквадратичным отклонением, что-то явно не так :)

2021-09-24 09:48 UTC, ElenaBakova commented on Semester3/Homework1/MatrixMultiplication/Matrix.cs
> +            using (StreamReader stream = File.OpenText(path))
Я это исправила и CI перестал работать

2021-09-27 14:16 UTC, yurii-litvinov commented on Semester3/Homework1/MatrixMultiplication/MethodsComparison.cs
> +    class MethodsComparison
```suggestion
    static class MethodsComparison
```

2021-09-27 14:16 UTC, yurii-litvinov commented on Semester3/Homework1/MatrixMultiplication/MethodsComparison.cs
> +                for (int j = i; j <= 2000; j += 500)
Сколько тут магических констант...

2021-09-27 14:16 UTC, yurii-litvinov commented on Semester3/Homework1/MatrixMultiplication/Program.cs
> +               string secoindMatrixPath;
```suggestion
               string seco
               ndMatrixPath;
```

2021-09-27 14:17 UTC, yurii-litvinov approved these changes
Окей, сейчас в целом всё так, зачтена

2021-09-28 22:16 UTC, merged